# Generated by Django 3.2.17 on 2023-02-15 20:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=15)),
                ('order_number', models.IntegerField()),
                ('order_number_internal', models.IntegerField()),
                ('client_address', models.CharField(max_length=50)),
                ('client_address_2', models.CharField(max_length=50)),
                ('client_city', models.CharField(max_length=50)),
                ('client_zip', models.CharField(max_length=10)),
                ('client_state', models.CharField(max_length=15)),
                ('client_email', models.CharField(max_length=20)),
                ('client_phone', models.CharField(max_length=10)),
                ('total_cost', models.IntegerField()),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('date_started', models.DateField(default=datetime.date.today)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.status')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('product', models.ManyToManyField(to='catalog.Product')),
            ],
        ),
    ]
