# Generated by Django 3.2.18 on 2023-02-20 19:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='date_closed_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='back_pdf',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='front_pdf',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='design_1_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.imagedesign'),
            preserve_default=False,
        ),
    ]
