# Generated by Django 3.2.18 on 2023-02-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230220_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='client_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client_address_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client_email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client_state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='client_zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
