# Generated by Django 3.2.17 on 2023-02-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_store_cart_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=15)),
                ('order_number', models.IntegerField()),
                ('order_number_internal', models.IntegerField()),
                ('client_address', models.CharField(max_length=50)),
                ('client_address_2', models.CharField(max_length=50)),
                ('client_city', models.CharField(max_length=50)),
                ('client_zip', models.CharField(max_length=10)),
                ('client_state', models.CharField(max_length=15)),
                ('client_email', models.CharField(max_length=20)),
                ('client_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
