# Generated by Django 3.2.17 on 2023-02-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20230214_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
