# Generated by Django 3.2.18 on 2023-02-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20230220_2059'),
        ('order', '0004_alter_cart_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.invoice'),
        ),
    ]
