# Generated by Django 3.2.18 on 2023-02-21 19:59

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_cart_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='order_number_internal',
            field=models.CharField(default=order.models.pkgen, max_length=6, primary_key=True, serialize=False),
        ),
    ]
