# Generated by Django 3.2.18 on 2023-02-22 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_method', models.CharField(choices=[('MANUAL', 'manual'), ('API', 'api')], max_length=7)),
                ('date_uploaded', models.DateField(default=datetime.date.today)),
                ('api_upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.apiupload')),
                ('file_upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.fileupload')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart')),
            ],
        ),
    ]
