# Generated by Django 3.2.18 on 2023-02-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='upload_method',
            field=models.CharField(choices=[('MANUAL', 'manual'), ('API', 'api')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
