# Generated by Django 3.2.18 on 2023-02-20 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cart_total_cost'),
        ('upload', '0002_uploadedfile_upload_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='status',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='date_uploaded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
    ]
