# Generated by Django 3.2.18 on 2023-02-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('upload', '0002_uploadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='api_upload',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.apiupload'),
        ),
        migrations.DeleteModel(
            name='ApiUpload',
        ),
    ]
