# Generated by Django 3.2.18 on 2023-02-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_approved',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_paid',
            field=models.DateField(null=True),
        ),
    ]
