# Generated by Django 3.2.17 on 2023-02-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='data_approved',
            new_name='date_approved',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='data_paid',
            new_name='date_paid',
        ),
    ]
