# Generated by Django 3.2.18 on 2023-02-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymentmethod',
            name='customer',
            field=models.JSONField(null=True),
        ),
    ]
